# Generated by Django 6.0.3 on 2026-04-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SesionIdeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surfista', models.CharField(max_length=128)),
                ('alias', models.CharField(max_length=100)),
                ('fecha_referencia', models.DateField()),
                ('zona_referencia', models.CharField(default='Costa da Morte', max_length=50)),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=4)),
                ('periodo', models.IntegerField()),
                ('marea', models.CharField(max_length=50)),
                ('direccion_viento', models.CharField(max_length=50)),
                ('estado_viento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_match', models.DateTimeField()),
                ('altura_real', models.DecimalField(decimal_places=2, max_digits=4)),
                ('periodo_real', models.IntegerField()),
                ('viento_real', models.DecimalField(decimal_places=2, max_digits=4)),
                ('leido_en_zona', models.CharField(max_length=100)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('sesion_ideal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sesionideal')),
            ],
        ),
    ]
