# Generated by Django 6.0.3 on 2026-04-07 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surfista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=100, unique=True)),
                ('nombre_usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SesionIdeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('fecha_referencia', models.DateField()),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=4)),
                ('periodo', models.IntegerField()),
                ('marea', models.CharField(max_length=50)),
                ('direccion_viento', models.CharField(max_length=50)),
                ('estado_viento', models.CharField(max_length=50)),
                ('surfista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.surfista')),
            ],
        ),
    ]
