# Generated by Django 6.0.3 on 2026-04-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionideal',
            name='zona_referencia',
            field=models.CharField(default='Costa da Morte', max_length=50),
        ),
    ]
