# Generated by Django 6.0.3 on 2026-04-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sesionideal_zona_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_match', models.DateTimeField()),
                ('altura_real', models.DecimalField(decimal_places=2, max_digits=4)),
                ('periodo_real', models.IntegerField()),
                ('viento_real', models.DecimalField(decimal_places=2, max_digits=4)),
                ('leido_en_zona', models.CharField(max_length=100)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('sesion_ideal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sesionideal')),
            ],
        ),
    ]
